### ISSUE TITLE
wdio-gmail-service its not in https://www.npmjs.com/

### ISSUE THREAD

**Issue by eduardo-castaneda** [webdriverio-community/wdio-gmail-service#17]
I've tried to install this plugin without success. Part of the problem it's that its not in npmjs or yarnpkg.

Could you please expand README to explain how to install and configure?

**Comment by christian-bromann** [comment]
@hughleo based on our private conversation on Twitter what do you think is missing for this to be released? From a quick look into the code base the only thing that would be *nice to have* is an e2e test for this.

**Comment by hughleo** [comment]
hi @christian-bromann, yes for now that would be it. Haven't had a chance to look at any other potential improvements. What actually needs done to release?

**Comment by christian-bromann** [comment]
> What actually needs done to release?

I pushed some minor clean up commits and added unit tests. Everything was in place already, so just had to hit the release pipeline. It is no on NPM as `v1.0.0`.

Thanks for all the work @hughleo 👏
